-- MySQL Script generated by MySQL Workbench
-- Fri Dec 29 16:45:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flasksitio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flasksitio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flasksitio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flasksitio` ;

-- -----------------------------------------------------
-- Table `flasksitio`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flasksitio`.`admins` (
  `adminid` INT NOT NULL AUTO_INCREMENT,
  `adminname` VARCHAR(255) NOT NULL,
  `adminpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`adminid`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flasksitio`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flasksitio`.`contactos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombrecompleto` VARCHAR(60) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `fechacreacion` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flasksitio`.`turnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flasksitio`.`turnos` (
  `idturno` INT NOT NULL AUTO_INCREMENT,
  `contactonombrecompleto` VARCHAR(60) NOT NULL,
  `fechacreacionturno` DATETIME NOT NULL,
  `fechaturno` DATE NOT NULL,
  `desde` TIME NOT NULL,
  `hasta` TIME NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idturno`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
